/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-sequelize6 dev) on 2021-12-04 06:59:13.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Nft extends Model {
}

module.exports = (sequelize) => {
  return Nft.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    tokenId: {
      type: DataTypes.STRING(191)
    },
    owner: {
      type: DataTypes.STRING(191)
    },
    name: {
      type: DataTypes.STRING(191)
    },
    image: {
      type: DataTypes.STRING(191)
    },
    description: {
      type: DataTypes.STRING(191)
    }
  }, {
    sequelize: sequelize,
    modelName: 'Nft',
    tableName: 'nfts',
    indexes: [
      {
        name: 'nfts_onwer_indexes',
        fields: ['owner']
      }
    ],
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })
}
