/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-sequelize6 dev) on 2021-12-04 06:59:13.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Offer extends Model {
}

module.exports = (sequelize) => {
  return Offer.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    offerId: {
      type: DataTypes.INTEGER
    },
    status: {
      type: DataTypes.STRING(191)
    },
    offeror: {
      type: DataTypes.STRING(191)
    },
    offerorNftContract: {
      type: DataTypes.STRING(191)
    },
    offerorNft: {
      type: DataTypes.STRING(191)
    },
    offerorHands: {
      type: DataTypes.STRING(191)
    },
    offeree: {
      type: DataTypes.STRING(191)
    },
    offereeNftContract: {
      type: DataTypes.STRING(191)
    },
    offereeNft: {
      type: DataTypes.STRING(191)
    },
    offereeHands: {
      type: DataTypes.STRING(191)
    },
    drawPoint: {
      type: DataTypes.INTEGER
    },
    winner: {
      type: DataTypes.STRING(191)
    }
  }, {
    sequelize: sequelize,
    modelName: 'Offer',
    tableName: 'offers',
    indexes: [
      {
        name: 'offers_offeror_indexes',
        fields: ['offeror']
      },
      {
        name: 'offers_offeree_indexes',
        fields: ['offeree']
      }
    ],
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })
}
